image: Visual Studio 2015
version: '{branch}.{build}'

clone_folder: C:\projects\xdebug

install:
    ps: .appveyor\install.ps1

cache:
  - C:\build-cache -> .appveyor.yml, .appveyor\install.ps1

environment:
    BIN_SDK_VER: 2.2.0
    matrix:
        - PHP_VER: master
          ARCH: x64
          TS: 1
          VC: vs16
          OPCACHE: yes
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
        - PHP_VER: master
          ARCH: x64
          TS: 0
          VC: vs16
          OPCACHE: yes
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
        - PHP_VER: master
          ARCH: x64
          TS: 1
          VC: vs16
          OPCACHE: no
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
        - PHP_VER: master
          ARCH: x64
          TS: 0
          VC: vs16
          OPCACHE: no
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
        - PHP_VER: master
          ARCH: x86
          TS: 1
          VC: vs16
          OPCACHE: no
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
        - PHP_VER: master
          ARCH: x86
          TS: 0
          VC: vs16
          OPCACHE: yes
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
        - PHP_VER: 7.4
          ARCH: x64
          TS: 1
          VC: vc15
          OPCACHE: yes
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - PHP_VER: 7.4
          ARCH: x64
          TS: 0
          VC: vc15
          OPCACHE: yes
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - PHP_VER: 7.4
          ARCH: x64
          TS: 1
          VC: vc15
          OPCACHE: no
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - PHP_VER: 7.4
          ARCH: x64
          TS: 0
          VC: vc15
          OPCACHE: no
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - PHP_VER: 7.4
          ARCH: x86
          TS: 1
          VC: vc15
          OPCACHE: no
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - PHP_VER: 7.4
          ARCH: x86
          TS: 0
          VC: vc15
          OPCACHE: yes
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - PHP_VER: 7.3
          ARCH: x64
          TS: 1
          VC: vc15
          OPCACHE: yes
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - PHP_VER: 7.3
          ARCH: x64
          TS: 0
          VC: vc15
          OPCACHE: no
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - PHP_VER: 7.3
          ARCH: x86
          TS: 1
          VC: vc15
          OPCACHE: no
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - PHP_VER: 7.3
          ARCH: x86
          TS: 0
          VC: vc15
          OPCACHE: yes
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - PHP_VER: 7.2
          ARCH: x64
          TS: 1
          VC: vc15
          OPCACHE: yes
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - PHP_VER: 7.2
          ARCH: x64
          TS: 0
          VC: vc15
          OPCACHE: no
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - PHP_VER: 7.2
          ARCH: x86
          TS: 1
          VC: vc15
          OPCACHE: no
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - PHP_VER: 7.2
          ARCH: x86
          TS: 0
          VC: vc15
          OPCACHE: yes
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

build_script:
    ps: .appveyor\build.ps1

after_build:
    ps: .appveyor\package.ps1

test_script:
    ps: .appveyor\test.ps1
