language: php

php:
  - 7.0
  - 7.1
  - nightly

env:
  matrix:
    -
    - VALGRIND=1 SKIP_DBGP_TESTS=1

matrix:
  allow_failures:
    - php: nightly

install:
  - if [ "$VALGRIND" -eq 1 ]; then sudo apt-get update -qq; sudo apt-get install -qq valgrind; export TEST_PHP_ARGS="-m"; valgrind --version; fi

before_script:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - ./.travis.scripts/compile.sh

notifications:
  email:
    derick@xdebug.org

script:
  - MYPHP=`make findphp`
  - export PATH=`dirname $MYPHP`:$PATH
  - $MYPHP -c /tmp/temp-php-config.ini -v
  - REPORT_EXIT_STATUS=1 TEST_PHP_EXECUTABLE=$MYPHP $MYPHP -c /tmp/temp-php-config.ini -dxdebug.auto_trace=0 run-tests.php -q -x --show-diff

notifications:
  irc: "irc.freenode.net#xdebug"
