sudo: false

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

env:
  - USE_OPCACHE=0
  - USE_OPCACHE=1

before_script:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - sh -e ./.travis.scripts/compile.sh

notifications:
  email:
    derick@xdebug.org

script:
  - MYPHP=`make findphp`
  - export PATH=`dirname $MYPHP`:$PATH
  - export TEST_PHP_ARGS="-d foo=1 -n -d zend_extension=opcache.so -d opcache.enable=${USE_OPCACHE} -d opcache.enable_cli=${USE_OPCACHE} -d zend_extension=$PWD/modules/xdebug.so -d xdebug.auto_trace=0"
  - export SKIP_IPV6_TESTS=1
  - $MYPHP $TEST_PHP_ARGS -v
  - REPORT_EXIT_STATUS=1 TEST_PHP_EXECUTABLE=$MYPHP $MYPHP -n run-tests.php -q -x --show-diff

after_script:
  - ./.travis.scripts/show-errors.sh

notifications:
  irc: "chat.freenode.net#xdebug"
